;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        easy-kill
        helm-M-x
        helm-confirm-and-exit-minibuffer
        kill-region
        org-delete-char
        org-self-insert-command
        prelude-move-beginning-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        ))
